imports:
  # all app-related parameters are included by this file
  - { resource: 'app.yaml' }
services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: true

  App\Service\Commission\:
    resource: '../src/Service/Commission/'
    exclude:
      - '../src/Service/Commission/DTO/'
      - '../src/Service/Commission/Reader/'

  App\Service\Commission\CommissionManager:
    class: App\Service\Commission\CommissionManager
    arguments:
      $rateProvider: '@App\Service\Commission\ExternalApi\ExchangeRateProvider\ExchangeRateCachedProvider'
      $batchSize: '%default_batch_size%'

  App\Service\Commission\RateCalculator\CountryFeeManager:
    class: App\Service\Commission\RateCalculator\CountryFeeManager
    arguments:
      $europeanCountries: '%european_countries%'
      $europeanCountryFee: '%european_country_fee%'
      $nonEuropeanCountryFee: '%non_european_country_fee%'

  App\Service\Commission\RateCalculator\EuropeanRelatedRateCalculator:
    class: App\Service\Commission\RateCalculator\EuropeanRelatedRateCalculator
    arguments:
      $baseCurrency: '%base_currency%'
      $scale: '%calculation_precision%'
      $precision: '%calculation_round%'

  App\Service\Commission\ExternalApi\CountryProvider\BinlistProvider:
    class: App\Service\Commission\ExternalApi\CountryProvider\BinlistProvider
    arguments:
      $client: "@guzzle_binlist_client"

  App\Service\Commission\ExternalApi\ExchangeRateProvider\ExchangeRatesProvider:
    class: App\Service\Commission\ExternalApi\ExchangeRateProvider\ExchangeRatesProvider
    arguments:
      $client: "@guzzle_exchange_rates_client"
      $baseCurrency: "%base_currency%"

  App\Service\Commission\ExternalApi\ExchangeRateProvider\ExchangeRateCachedProvider:
    class: App\Service\Commission\ExternalApi\ExchangeRateProvider\ExchangeRateCachedProvider
    arguments:
      $realProvider: '@App\Service\Commission\ExternalApi\ExchangeRateProvider\ExchangeRatesProvider'
      $cacheTTL: '%rate_cache_ttl%'

  guzzle_binlist_client:
    class: GuzzleHttp\Client
    arguments:
      $config:
        base_uri: '%binlist_base_uri%'
        http_errors: false

  guzzle_exchange_rates_client:
    class: GuzzleHttp\Client
    arguments:
      $config:
        base_uri: '%exchange_rates_base_uri%'
        http_errors: false
