imports:
  # all app-related parameters are included by this file
  - { resource: 'app.yaml' }
services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: true

  App\Service\Commission\:
    resource: '../src/Service/Commission/'
    exclude:
      - '../src/Service/Commission/DTO/'
      - '../src/Service/Commission/Reader/'

  App\Service\Commission\CommissionManager:
    class: App\Service\Commission\CommissionManager
    arguments:
      $rateProvider: '@App\Service\Commission\ExternalApi\ExchangeRateProvider\ExchangeRateCachedProvider'
      $batchSize: '%default_batch_size%'

  App\Service\Commission\RateCalculator\CountryFeeManager:
    class: App\Service\Commission\RateCalculator\CountryFeeManager
    arguments:
      $europeanCountries: '%european_countries%'
      $europeanCountryFee: '%european_country_fee%'
      $nonEuropeanCountryFee: '%non_european_country_fee%'

  App\Service\Commission\RateCalculator\EuropeanRelatedRateCalculator:
    class: App\Service\Commission\RateCalculator\EuropeanRelatedRateCalculator
    arguments:
      $baseCurrency: '%base_currency%'
      $scale: '%calculation_precision%'
      $precision: '%calculation_round%'

  App\Service\Commission\ExternalApi\CountryProvider\BinlistProvider:
    class: App\Service\Commission\ExternalApi\CountryProvider\BinlistProvider
    arguments:
      $client: "@guzzle_binlist_client"

  App\Service\Commission\ExternalApi\ExchangeRateProvider\ExchangeRatesProvider:
    class: App\Service\Commission\ExternalApi\ExchangeRateProvider\ExchangeRatesProvider
    arguments:
      $client: "@guzzle_exchange_rates_client"
      $baseCurrency: "%base_currency%"

  App\Service\Commission\ExternalApi\ExchangeRateProvider\ExchangeRateCachedProvider:
    class: App\Service\Commission\ExternalApi\ExchangeRateProvider\ExchangeRateCachedProvider
    arguments:
      $realProvider: '@App\Service\Commission\ExternalApi\ExchangeRateProvider\ExchangeRatesProvider'
      $cacheTTL: '%rate_cache_ttl%'

  guzzle_binlist_client:
    class: GuzzleHttp\Client
    arguments:
      $config:
        base_uri: '%binlist_base_uri%'
        http_errors: false

  guzzle_exchange_rates_client:
    class: GuzzleHttp\Client
    arguments:
      $config:
        base_uri: '%exchange_rates_base_uri%'
        http_errors: false

  App\Command\NumberOutputCommand:
    class: App\Command\NumberOutputCommand
    arguments:
      $taskOneManager: '@number_printer_manager_task_one'
      $taskTwoManager: '@number_printer_manager_task_two'
      $taskThreeManager: '@number_printer_manager_task_three'
    tags:
      - { name: 'console.command', command: 'app:numbers' }

  number_printer_manager_task_one:
    class: App\Service\NumberPrinter\NumberPrintManager
    arguments:
      $middleware: '@middleware_task_one'
      $stringCompiler: '@spaces_compiler'

  number_printer_manager_task_two:
    class: App\Service\NumberPrinter\NumberPrintManager
    arguments:
      $middleware: '@middleware_task_two'
      $stringCompiler: '@dashes_compiler'

  number_printer_manager_task_three:
    class: App\Service\NumberPrinter\NumberPrintManager
    arguments:
      $middleware: '@middleware_task_three'
      $stringCompiler: '@dashes_compiler'

  middleware_task_one:
    class: App\Service\NumberPrinter\Middleware\GeneratorMiddleware
    arguments:
      $printer: '@printer_task_one'

  middleware_task_two:
    class: App\Service\NumberPrinter\Middleware\GeneratorMiddleware
    arguments:
      $printer: '@printer_task_two'

  middleware_task_three:
    class: App\Service\NumberPrinter\Middleware\GeneratorMiddleware
    arguments:
      $printer: '@printer_task_three'

  printer_task_one:
    class: App\Service\NumberPrinter\Printer\ConditionPrinter
    arguments:
      $conditionOne: '@condition_divided_by_three'
      $outputOne: 'pa'
      $conditionTwo: '@condition_divided_by_five'
      $outputTwo: 'pow'

  printer_task_two:
    class: App\Service\NumberPrinter\Printer\ConditionPrinter
    arguments:
      $conditionOne: '@condition_divided_by_two'
      $outputOne: 'hatee'
      $conditionTwo: '@condition_divided_by_seven'
      $outputTwo: 'ho'

  printer_task_three:
    class: App\Service\NumberPrinter\Printer\ConditionPrinter
    arguments:
      $conditionOne: '@one_of_one_four_nine'
      $outputOne: 'joff'
      $conditionTwo: '@larger_then_five_condition'
      $outputTwo: 'tchoff'

  larger_then_five_condition:
    class: App\Service\NumberPrinter\Conditions\LargerThanCondition
    arguments:
      $compareTo: 5

  one_of_one_four_nine:
    class: App\Service\NumberPrinter\Conditions\OneOfCondition
    arguments:
      $values:
        - 1
        - 4
        - 9

  condition_divided_by_two:
    class: App\Service\NumberPrinter\Conditions\NumberDividesCondition
    arguments:
      $divideBy: 2

  condition_divided_by_three:
    class: App\Service\NumberPrinter\Conditions\NumberDividesCondition
    arguments:
      $divideBy: 3

  condition_divided_by_five:
    class: App\Service\NumberPrinter\Conditions\NumberDividesCondition
    arguments:
      $divideBy: 5

  condition_divided_by_seven:
    class: App\Service\NumberPrinter\Conditions\NumberDividesCondition
    arguments:
      $divideBy: 7

  spaces_compiler:
    class: App\Service\NumberPrinter\StringCompiler\SeparatorCompiler
    arguments:
      $separator: ' '

  dashes_compiler:
    class: App\Service\NumberPrinter\StringCompiler\SeparatorCompiler
    arguments:
      $separator: '-'
